---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: filebeat
  gather_facts: false
  tasks:
  - name: "Filebeat test output"
    become: true
    command: /usr/bin/filebeat test output
    register: test_output_result
  - name: Filebeat test output success
    assert:
      that: "'talk to server... OK' in test_output_result.stdout"
